on:
  push:
    branches:
      - r





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd


       

      - name: "Testing Printing"
        run: echo rahma 

    



