on:
  push:
    branches:
      - r





jobs:
  build:
    runs-on: ubutu-latest

    steps:
      - name: 'after'
        run: ls


      - uses: actions/checkout@v3 

      - name: "Login to Docker hub"
        run: docker login --username rahmaashraf --password dckr_pat__0BiRlaSt2uKaWzc4q7afLPTtjA



