on:
  push:
    branches:
      - r





jobs:
  build:
    runs-on: ubutu-latest

    steps:
      - name: 'after'
        run: ls


      - uses: actions/checkout@v3 

      - name: 'after'
        run: ls



